export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  SSH_CONNECTION_FAILED: "SSH_CONNECTION_FAILED",
  SSH_HOST_KEY_MISMATCH: "SSH_HOST_KEY_MISMATCH",
  OPERATION_NOT_SUPPORTED: "OPERATION_NOT_SUPPORTED",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
